# Generated by Django 5.2.4 on 2025-07-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_administrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='nombre_mostrar',
            field=models.CharField(blank=True, help_text='Opcional. Si se deja vacío, se usará nombre + apellido del usuario.', max_length=150),
        ),
    ]
