# Generated by Django 5.2.4 on 2025-07-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_administrador_telefono_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='nombre_mostrar',
        ),
        migrations.AddField(
            model_name='administrador',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='administrador',
            name='nombres',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
